### PR TITLE
Fix `HexagonGrid` centered layout

### LINKED ISSUE #22: `HexagonGrid` is built without margin offset

### PR DESCRIPTION
**Pull request by gallottino**
Closes #22

### CODE REVIEW

File: lib/screens/level.dart [hunk 1]
```diff
@@ -104,7 +103,6 @@ class _LevelState extends State<Level> with TickerProviderStateMixin {
             Flexible(
                 flex: 8,
                 child: GameGrid(
-                    gameGrid: null,
```
Comment (gallottino) [inline lib/screens/level.dart:106]: Unused field. I removed it.

File: lib/screens/tutorial.dart [hunk 2]
```diff
@@ -161,25 +159,24 @@ class _TutorialState extends State<Tutorial> {
...
-                      Themes().planets[0].gradient_1,
-                      Themes().planets[0].gradient_2,
-                    ],
-                  )),
-                child: status < totalStatus() - 1 ? GameGrid(
-                gameGrid: null,
-                gameLogic: tutorialLogic,
-                currentTheme: Themes().planets[0],
-                onClick: onTutorialClick ): Container()),
+            Container(
```
Comment (gallottino) [inline lib/screens/tutorial.dart:164]: Just a flutter format.

**Review by Oniryu95 — APPROVED** [review]
